### ISSUE TITLE
data from fetch api call not passing to react app component

### ISSUE THREAD

**Issue by Fozz-byte** [Fozz-byte/front-end-project#1]
The **getListing** method should receive **listings data** from the parsed **local data.json** file within the **data.js** file and pass it to the empty listings array to be rendered by the **InquiresList** instance. It is not currently functioning with imported data, only with hard-coded data.

![Screenshot 2022-04-24 at 22 26 30](https://user-images.githubusercontent.com/64425153/164997350-c970d469-7e50-4c49-a124-6565cc7d759c.png)

**Comment by fitiskin** [comment]
Hello, @Fozz-byte 

To make it work please consider this things:

1. There is no `jsonResponse.listings` in your JSON, only `jsonResponse.data`:

```js
// from
return jsonResponse.listings.map(listing => ({
```

```js
// to
return jsonResponse.data.map(listing => ({
```

2. You do have to call `getListing()` method inside your `App.js` component to fetch the data. I suggest using [componentDidMount](https://reactjs.org/docs/react-component.html#componentdidmount) method from the React.Component lifecycle for this purpose:

```js
componentDidMount() {
  this.getListing();
}
```

I hope this helps.

UPD

You can place the `data.json` near to `Data.js` (at least the`/src` folder) and just import its content without making any requests (I prefer this method for serving local JSON data for that environment). You can get rid of async method `getListing()`, requests and promises.

Data.js:

```js
import jsonResponse from "./data.json";

const Data = {
  getListing() {
    if (jsonResponse.data) {
      return jsonResponse.data.map((listing) => ({
        id: listing.id,
        imageSrc: listing.photo_small,
        title: listing.title,
        startDate: listing.terms.start_date,
        endDate: listing.terms.end_date,
        user: listing.user.first_name,
        updatedAt: listing.updated_at,
        lastMessage: listing.last_message.message,
      }));
    }
  },
};

export default Data;
```

App.js constructor:

```js
constructor(props) {
  super(props);

  this.state = {
    listings: Data.getListing(),
  };
}
```

**Comment by Fozz-byte** [comment]
Hello, @fitiskin, thank you for the detailed response and refactoring suggestions. Now it makes sense! I appreciate you taking the time to help a newbie out.
